# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Pipeline that publishes de AML Pipeline that will generate the forecast

# trigger:
#   branches:
#     include:
#     - v2-preview
#   paths:
#     include:
#     - Custom_Script/mlops-pipelines/4-batch-forecasting-code-build/*
#     - Custom_Script/mlops-pipelines/scripts/create_forecasting_pipeline.py
#     - Custom_Script/scripts/forecast.py
#     - Custom_Script/scripts/forecast.conda.yml
#     - Custom_Script/scripts/utils/forecasting.py

variables:
- template: ../many-models-variables.yml
- group: manymodels-vg

pool:
  vmImage: ubuntu-latest

stages:
- stage: build_forecasting
  displayName: 'Publish Forecasting AML Pipeline'
  jobs:
    - job: build_forecasting
      displayName: 'Publish Forecasting AML Pipeline'
      steps:

        - task: UsePythonVersion@0
          displayName: 'Use Python 3.7'
          inputs:
            versionSpec: 3.7

        - task: AzureCLI@1
          displayName: 'Publish Forecasting AML Pipeline'
          inputs:
            azureSubscription: $(SERVICECONNECTION_WORKSPACE)
            scriptLocation: inlineScript
            inlineScript: |
              # Install dependencies
              python -m pip install --upgrade pip && python -m pip install azureml-sdk[contrib]==$SDK_VERSION
              # Create/update forecasting pipeline
              forecastingbuild_script=Custom_Script/mlops-pipelines/scripts/create_forecasting_pipeline.py
              python $forecastingbuild_script --name $(AML_FORECASTING_PIPELINE_NAME) \
                                              --version $(Build.BuildId) \
                                              --dataset $(AML_DATASET_NAME) \
                                              --compute $(AML_COMPUTE_NAME) \
                                              --subscription-id $(az account show --query id -o tsv) \
                                              --resource-group $(RESOURCE_GROUP) \
                                              --workspace-name $(AMLWORKSPACE_NAME)

