# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Azure Pipeline Template for ML Workspace Resources Deployment

jobs:

- job: iac_build
  displayName: 'IaC Build'
  steps:
  - task: CopyFiles@2
    displayName: 'Copy ARM templates'
    inputs:
      sourceFolder: 'mlops-pipelines/1-setup/arm-templates'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
  - publish: '$(Build.ArtifactStagingDirectory)'
    artifact: infratemplates

- deployment: iac_deployment
  displayName: 'IaC Deployment'
  environment: $(ENVIRONMENT)
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: infratemplates
        
        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Storage Account'
          inputs:
            azureSubscription: $(SERVICECONNECTION_GROUP)
            resourceGroupName: $(RESOURCE_GROUP)
            location: $(LOCATION)
            csmFile: '$(Pipeline.Workspace)/infratemplates/storage.template.json'
            csmParametersFile: '$(Pipeline.Workspace)/infratemplates/storage.parameters.json'
            overrideParameters: '-name $(STORAGEACCOUNT_NAME) -location $(LOCATION)'

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Key Vault'
          inputs:
            azureSubscription: $(SERVICECONNECTION_GROUP)
            resourceGroupName: $(RESOURCE_GROUP)
            location: $(LOCATION)
            csmFile: '$(Pipeline.Workspace)/infratemplates/keyvault.template.json'
            csmParametersFile: '$(Pipeline.Workspace)/infratemplates/keyvault.parameters.json'
            overrideParameters: '-name $(KEYVAULT_NAME) -location $(LOCATION)'

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Application Insights'
          inputs:
            azureSubscription: $(SERVICECONNECTION_GROUP)
            resourceGroupName: $(RESOURCE_GROUP)
            location: $(LOCATION)
            csmFile: '$(Pipeline.Workspace)/infratemplates/appinsights.template.json'
            overrideParameters: '-name $(APPINSIGHTS_NAME) -location $(LOCATION)'
        
        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Container Registry'
          inputs:
            azureSubscription: $(SERVICECONNECTION_GROUP)
            resourceGroupName: $(RESOURCE_GROUP)
            location: $(LOCATION)
            csmFile: '$(Pipeline.Workspace)/infratemplates/containerregistry.template.json'
            overrideParameters: '-name $(CONTAINERREGISTRY_NAME) -location $(LOCATION)'

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy AML Workspace'
          inputs:
            azureSubscription: $(SERVICECONNECTION_GROUP)
            resourceGroupName: $(RESOURCE_GROUP)
            location: $(LOCATION)
            csmFile: '$(Pipeline.Workspace)/infratemplates/mlworkspace.template.json'
            overrideParameters: '-workspaceName $(AMLWORKSPACE_NAME) -keyVaultName $(KEYVAULT_NAME) -appInsightsName $(APPINSIGHTS_NAME) -containerRegistryName $(CONTAINERREGISTRY_NAME) -storageAccountName $(STORAGEACCOUNT_NAME)'
